title = "Local configuration"

[bind_public]
http_interface = "127.0.0.1"
http_port = 1234
http_read_timeout_ms = 10000
http_write_timeout_ms = 10000
http_max_header_bytes = 8192
https_enabled = false
max_body_bytes = 1048576

[bind_public.http_cors]
enabled = true
allowed_origins = "*"
allowed_methods = ["GET", "HEAD", "POST"]
allowed_headers = ["Content-type", "X-Oasis-Insecure-Auth", "X-Oasis-Session-Key"]
exposed_headers = []
max_age = -1
allowed_credentials = true

[bind_private]
http_interface = "127.0.0.1"
http_port = 1235
http_read_timeout_ms = 10000
http_write_timeout_ms = 10000
http_max_header_bytes = 8192
https_enabled = false
max_body_bytes = 8192

[backend]
provider = "ethereum"

[eth]
url = "wss://web3.oasiscloud.io/ws"

[eth.wallet]
private_keys = [ "b5144c6bda090723de712e52b92b4c758d78348ddce9aa80ca8ef51125bfb308" ]

[mailbox]
provider = "mem"

[auth]
provider = "insecure"
