title = "Local configuration"

[bind_public]
http_interface = "127.0.0.1"
http_port = 1234
http_read_timeout_ms = 10000
http_write_timeout_ms = 10000
http_max_header_bytes = 8192
https_enabled = true
tls_private_key_path = "/config/tls/private.pem"
tls_certificate_path = "/config/tls/cert.pem"

[bind_private]
http_interface = "127.0.0.1"
http_port = 1235
http_read_timeout_ms = 10000
http_write_timeout_ms = 10000
http_max_header_bytes = 8192
https_enabled = false
tls_private_key_path = "/config/tls/private.pem"
tls_certificate_path = "/config/tls/cert.pem"

[backend]
provider = "ethereum"

[eth]
url = "wss://web3.beta.oasiscloud-staging.net/ws"

[eth.wallet]
private_keys = [ ]

[mailbox]
provider = "mem"

[auth]
provider = "insecure"
